-- Seed for employee information management tables.
-- Uses the existing employee from V1_3_1__employee_seed.sql.

INSERT INTO employee.employee_profiles (
    employee_id,
    tenant_id,
    employee_code,
    first_name,
    middle_name,
    last_name,
    full_name,
    arabic_name,
    profile_photo_path,
    gender_id,
    date_of_birth,
    marital_status_id,
    nationality_id,
    blood_group,
    personal_email,
    official_email,
    primary_mobile_number,
    secondary_mobile_number,
    alternate_contact_number,
    employee_status,
    date_of_joining,
    confirmation_date,
    probation_end_date,
    retirement_date,
    workforce_category,
    department_id,
    designation_id,
    job_title,
    is_active,
    created_by,
    updated_by
)
VALUES (
    '41111111-1111-1111-1111-111111111111',
    'default',
    'EMP-0001',
    'System',
    NULL,
    'Admin',
    'System Admin',
    NULL,
    NULL,
    (SELECT id FROM master_data.genders ORDER BY created_at LIMIT 1),
    DATE '1990-01-01',
    (SELECT id FROM master_data.marital_statuses ORDER BY created_at LIMIT 1),
    (SELECT id FROM master_data.nationalities ORDER BY created_at LIMIT 1),
    'O+',
    'system.personal@default.hrms',
    'system.admin@default.hrms',
    '+96890000001',
    '+96890000002',
    '+96890000003',
    'ACTIVE',
    DATE '2024-01-01',
    DATE '2024-06-01',
    DATE '2024-05-31',
    DATE '2050-12-31',
    'OMANI_NATIONAL',
    NULL,
    NULL,
    'HR Administrator',
    TRUE,
    'SYSTEM_SEED',
    'SYSTEM_SEED'
)
ON CONFLICT (tenant_id, employee_code) DO NOTHING;

INSERT INTO employee.employee_addresses (
    address_id,
    tenant_id,
    employee_id,
    address_type,
    flat_villa_number,
    building_name,
    street,
    area,
    city,
    state_province,
    country_id,
    postal_code,
    po_box,
    landmark,
    is_primary,
    is_active,
    created_by,
    updated_by
)
VALUES (
    '43000000-0000-0000-0000-000000000001',
    'default',
    '41111111-1111-1111-1111-111111111111',
    'CURRENT',
    'Villa 10',
    'Al Sawari Block',
    'Street 5',
    'Qurum',
    'Muscat',
    'Muscat',
    (SELECT id FROM master_data.countries ORDER BY created_at LIMIT 1),
    '100',
    '1234',
    'Near City Center',
    TRUE,
    TRUE,
    'SYSTEM_SEED',
    'SYSTEM_SEED'
)
ON CONFLICT (address_id) DO NOTHING;

INSERT INTO employee.employee_emergency_contacts (
    emergency_contact_id,
    tenant_id,
    employee_id,
    name,
    relationship_type_id,
    primary_mobile_number,
    secondary_mobile_number,
    email,
    address_line1,
    address_line2,
    city,
    country_id,
    is_primary,
    remarks,
    is_active,
    created_by,
    updated_by
)
VALUES (
    '43000000-0000-0000-0000-000000000002',
    'default',
    '41111111-1111-1111-1111-111111111111',
    'Ali Admin',
    (SELECT id FROM master_data.relationship_types ORDER BY created_at LIMIT 1),
    '+96890000004',
    NULL,
    'ali.admin@example.com',
    'Line 1',
    NULL,
    'Muscat',
    (SELECT id FROM master_data.countries ORDER BY created_at LIMIT 1),
    TRUE,
    'Primary emergency contact',
    TRUE,
    'SYSTEM_SEED',
    'SYSTEM_SEED'
)
ON CONFLICT (emergency_contact_id) DO NOTHING;

INSERT INTO employee.employee_dependants (
    dependant_id,
    tenant_id,
    employee_id,
    full_name,
    relationship_type_id,
    gender_id,
    date_of_birth,
    nationality_id,
    passport_number,
    civil_id_number,
    is_insurance_eligible,
    is_minor,
    effective_from,
    effective_to,
    status,
    remarks,
    is_active,
    created_by,
    updated_by
)
VALUES (
    '43000000-0000-0000-0000-000000000003',
    'default',
    '41111111-1111-1111-1111-111111111111',
    'Sara Admin',
    (SELECT id FROM master_data.relationship_types ORDER BY created_at LIMIT 1),
    (SELECT id FROM master_data.genders ORDER BY created_at LIMIT 1),
    DATE '2015-06-15',
    (SELECT id FROM master_data.nationalities ORDER BY created_at LIMIT 1),
    'P1234567',
    'C1234567',
    TRUE,
    TRUE,
    DATE '2025-01-01',
    DATE '2030-12-31',
    'ACTIVE',
    'Seed dependant',
    TRUE,
    'SYSTEM_SEED',
    'SYSTEM_SEED'
)
ON CONFLICT (dependant_id) DO NOTHING;

INSERT INTO employee.employee_beneficiaries (
    beneficiary_id,
    tenant_id,
    employee_id,
    full_name,
    relationship_type_id,
    date_of_birth,
    contact_number,
    email,
    address,
    identification_number,
    allocation_percentage,
    priority_order,
    is_active,
    remarks,
    created_by,
    updated_by
)
VALUES (
    '43000000-0000-0000-0000-000000000004',
    'default',
    '41111111-1111-1111-1111-111111111111',
    'Fatima Admin',
    (SELECT id FROM master_data.relationship_types ORDER BY created_at LIMIT 1),
    DATE '1988-03-10',
    '+96890000005',
    'fatima.admin@example.com',
    'Muscat, Oman',
    'ID-BEN-001',
    100.00,
    1,
    TRUE,
    'Seed beneficiary',
    'SYSTEM_SEED',
    'SYSTEM_SEED'
)
ON CONFLICT (beneficiary_id) DO NOTHING;

INSERT INTO employee.employee_workforce_details (
    workforce_detail_id,
    tenant_id,
    employee_id,
    workforce_category,
    pasi_number,
    pasi_registration_date,
    permit_number,
    permit_type,
    sponsor_name,
    sponsor_id,
    visa_status,
    work_permit_issue_date,
    work_permit_expiry_date,
    remarks,
    created_by,
    updated_by
)
VALUES (
    '43000000-0000-0000-0000-000000000005',
    'default',
    '41111111-1111-1111-1111-111111111111',
    'OMANI_NATIONAL',
    'PASI-0001',
    DATE '2024-01-15',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'Seed workforce detail',
    'SYSTEM_SEED',
    'SYSTEM_SEED'
)
ON CONFLICT (tenant_id, employee_id) DO NOTHING;

INSERT INTO employee.employee_documents (
    employee_document_id,
    tenant_id,
    employee_id,
    document_type,
    document_name,
    document_number,
    issuing_country_id,
    issuing_authority,
    issue_date,
    expiry_date,
    file_name,
    file_path,
    file_type,
    file_size,
    verification_status,
    verified_by,
    verified_date,
    alert_enabled,
    remarks,
    is_active,
    created_by,
    updated_by
)
VALUES (
    '43000000-0000-0000-0000-000000000006',
    'default',
    '41111111-1111-1111-1111-111111111111',
    'PASSPORT',
    'Passport Copy',
    'PASS-0001',
    (SELECT id FROM master_data.countries ORDER BY created_at LIMIT 1),
    'Royal Oman Police',
    DATE '2020-01-01',
    DATE '2030-01-01',
    'passport.pdf',
    'employee/default/41111111-1111-1111-1111-111111111111/passport.pdf',
    'application/pdf',
    204800,
    'VERIFIED',
    'SYSTEM_SEED',
    NOW(),
    TRUE,
    'Seed employee document',
    TRUE,
    'SYSTEM_SEED',
    'SYSTEM_SEED'
)
ON CONFLICT (employee_document_id) DO NOTHING;

INSERT INTO employee.employee_employment_history (
    employment_history_id,
    tenant_id,
    employee_id,
    action_type,
    old_department_id,
    new_department_id,
    old_designation_id,
    new_designation_id,
    old_location_id,
    new_location_id,
    old_grade_id,
    new_grade_id,
    old_manager_id,
    new_manager_id,
    effective_date,
    remarks,
    supporting_document_path,
    is_active,
    created_by,
    updated_by
)
VALUES (
    '43000000-0000-0000-0000-000000000007',
    'default',
    '41111111-1111-1111-1111-111111111111',
    'JOINING',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    DATE '2024-01-01',
    'Initial joining record',
    NULL,
    TRUE,
    'SYSTEM_SEED',
    'SYSTEM_SEED'
)
ON CONFLICT (employment_history_id) DO NOTHING;

INSERT INTO employee.employee_digital_onboarding (
    onboarding_id,
    tenant_id,
    employee_id,
    onboarding_status,
    eform_completed,
    document_upload_completed,
    policy_acknowledged,
    submitted_date,
    reviewed_date,
    approved_date,
    rejected_reason,
    remarks,
    created_by,
    updated_by
)
VALUES (
    '43000000-0000-0000-0000-000000000008',
    'default',
    '41111111-1111-1111-1111-111111111111',
    'COMPLETED',
    TRUE,
    TRUE,
    TRUE,
    NOW() - INTERVAL '5 days',
    NOW() - INTERVAL '4 days',
    NOW() - INTERVAL '3 days',
    NULL,
    'Seed onboarding complete',
    'SYSTEM_SEED',
    'SYSTEM_SEED'
)
ON CONFLICT (tenant_id, employee_id) DO NOTHING;

INSERT INTO employee.employee_policy_acknowledgements (
    acknowledgement_id,
    tenant_id,
    onboarding_id,
    policy_code,
    policy_version,
    accepted_flag,
    accepted_date_time,
    accepted_by,
    remarks,
    created_by
)
VALUES (
    '43000000-0000-0000-0000-000000000009',
    'default',
    '43000000-0000-0000-0000-000000000008',
    'HR-HANDBOOK',
    'v1.0',
    TRUE,
    NOW() - INTERVAL '5 days',
    'system.admin@default.hrms',
    'Seed policy accepted',
    'SYSTEM_SEED'
)
ON CONFLICT (acknowledgement_id) DO NOTHING;
