CREATE SEQUENCE IF NOT EXISTS employee.employee_code_seq START WITH 1000 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS employee.employee_profiles (
    employee_id UUID PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    employee_code VARCHAR(64) NOT NULL,
    first_name VARCHAR(128) NOT NULL,
    middle_name VARCHAR(128),
    last_name VARCHAR(128) NOT NULL,
    full_name VARCHAR(300),
    arabic_name VARCHAR(300),
    profile_photo_path VARCHAR(500),
    gender_id UUID,
    date_of_birth DATE,
    marital_status_id UUID,
    nationality_id UUID,
    blood_group VARCHAR(16),
    personal_email VARCHAR(255),
    official_email VARCHAR(255),
    primary_mobile_number VARCHAR(32),
    secondary_mobile_number VARCHAR(32),
    alternate_contact_number VARCHAR(32),
    employee_status VARCHAR(32) NOT NULL,
    date_of_joining DATE,
    confirmation_date DATE,
    probation_end_date DATE,
    retirement_date DATE,
    workforce_category VARCHAR(32) NOT NULL,
    department_id UUID,
    designation_id UUID,
    job_title VARCHAR(128),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(64) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by VARCHAR(64) NOT NULL,
    CONSTRAINT fk_employee_profiles_employee FOREIGN KEY (employee_id) REFERENCES employee.employees(id),
    CONSTRAINT uq_employee_profiles_tenant_code UNIQUE (tenant_id, employee_code),
    CONSTRAINT uq_employee_profiles_tenant_official_email UNIQUE (tenant_id, official_email),
    CONSTRAINT ck_employee_profiles_status CHECK (employee_status IN ('ACTIVE','INACTIVE','PROBATION','SUSPENDED','TERMINATED')),
    CONSTRAINT ck_employee_profiles_workforce CHECK (workforce_category IN ('OMANI_NATIONAL','EXPATRIATE')),
    CONSTRAINT ck_employee_profiles_confirmation_date CHECK (confirmation_date IS NULL OR date_of_joining IS NULL OR confirmation_date >= date_of_joining),
    CONSTRAINT ck_employee_profiles_probation_end_date CHECK (probation_end_date IS NULL OR date_of_joining IS NULL OR probation_end_date >= date_of_joining)
);

CREATE TABLE IF NOT EXISTS employee.employee_addresses (
    address_id UUID PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    employee_id UUID NOT NULL,
    address_type VARCHAR(32) NOT NULL,
    flat_villa_number VARCHAR(128),
    building_name VARCHAR(255),
    street VARCHAR(255),
    area VARCHAR(255),
    city VARCHAR(128) NOT NULL,
    state_province VARCHAR(128),
    country_id UUID NOT NULL,
    postal_code VARCHAR(32),
    po_box VARCHAR(32),
    landmark VARCHAR(255),
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(64) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by VARCHAR(64) NOT NULL,
    CONSTRAINT fk_employee_addresses_employee FOREIGN KEY (employee_id) REFERENCES employee.employees(id),
    CONSTRAINT ck_employee_addresses_type CHECK (address_type IN ('CURRENT','TEMPORARY','PERMANENT','WORK'))
);

CREATE TABLE IF NOT EXISTS employee.employee_emergency_contacts (
    emergency_contact_id UUID PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    employee_id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    relationship_type_id UUID NOT NULL,
    primary_mobile_number VARCHAR(32) NOT NULL,
    secondary_mobile_number VARCHAR(32),
    email VARCHAR(255),
    address_line1 VARCHAR(255),
    address_line2 VARCHAR(255),
    city VARCHAR(128),
    country_id UUID,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    remarks VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(64) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by VARCHAR(64) NOT NULL,
    CONSTRAINT fk_employee_emergency_contacts_employee FOREIGN KEY (employee_id) REFERENCES employee.employees(id)
);

CREATE TABLE IF NOT EXISTS employee.employee_dependants (
    dependant_id UUID PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    employee_id UUID NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    relationship_type_id UUID NOT NULL,
    gender_id UUID,
    date_of_birth DATE,
    nationality_id UUID,
    passport_number VARCHAR(128),
    civil_id_number VARCHAR(128),
    is_insurance_eligible BOOLEAN NOT NULL DEFAULT FALSE,
    is_minor BOOLEAN NOT NULL DEFAULT FALSE,
    effective_from DATE,
    effective_to DATE,
    status VARCHAR(32),
    remarks VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(64) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by VARCHAR(64) NOT NULL,
    CONSTRAINT fk_employee_dependants_employee FOREIGN KEY (employee_id) REFERENCES employee.employees(id),
    CONSTRAINT ck_employee_dependants_effective CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to >= effective_from)
);

CREATE TABLE IF NOT EXISTS employee.employee_beneficiaries (
    beneficiary_id UUID PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    employee_id UUID NOT NULL,
    full_name VARCHAR(255) NOT NULL,
    relationship_type_id UUID NOT NULL,
    date_of_birth DATE,
    contact_number VARCHAR(32),
    email VARCHAR(255),
    address VARCHAR(500),
    identification_number VARCHAR(128),
    allocation_percentage NUMERIC(5,2) NOT NULL,
    priority_order INTEGER,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    remarks VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(64) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by VARCHAR(64) NOT NULL,
    CONSTRAINT fk_employee_beneficiaries_employee FOREIGN KEY (employee_id) REFERENCES employee.employees(id),
    CONSTRAINT ck_employee_beneficiaries_allocation CHECK (allocation_percentage > 0)
);

CREATE TABLE IF NOT EXISTS employee.employee_workforce_details (
    workforce_detail_id UUID PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    employee_id UUID NOT NULL,
    workforce_category VARCHAR(32) NOT NULL,
    pasi_number VARCHAR(128),
    pasi_registration_date DATE,
    permit_number VARCHAR(128),
    permit_type VARCHAR(128),
    sponsor_name VARCHAR(255),
    sponsor_id VARCHAR(128),
    visa_status VARCHAR(128),
    work_permit_issue_date DATE,
    work_permit_expiry_date DATE,
    remarks VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(64) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by VARCHAR(64) NOT NULL,
    CONSTRAINT fk_employee_workforce_details_employee FOREIGN KEY (employee_id) REFERENCES employee.employees(id),
    CONSTRAINT uq_employee_workforce_details_tenant_employee UNIQUE (tenant_id, employee_id),
    CONSTRAINT ck_employee_workforce_details_category CHECK (workforce_category IN ('OMANI_NATIONAL','EXPATRIATE'))
);

CREATE TABLE IF NOT EXISTS employee.employee_documents (
    employee_document_id UUID PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    employee_id UUID NOT NULL,
    document_type VARCHAR(64) NOT NULL,
    document_name VARCHAR(255) NOT NULL,
    document_number VARCHAR(128),
    issuing_country_id UUID,
    issuing_authority VARCHAR(255),
    issue_date DATE,
    expiry_date DATE,
    file_name VARCHAR(255),
    file_path VARCHAR(500),
    file_type VARCHAR(128),
    file_size BIGINT,
    verification_status VARCHAR(32) NOT NULL,
    verified_by VARCHAR(64),
    verified_date TIMESTAMPTZ,
    alert_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    remarks VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(64) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by VARCHAR(64) NOT NULL,
    CONSTRAINT fk_employee_documents_employee FOREIGN KEY (employee_id) REFERENCES employee.employees(id),
    CONSTRAINT ck_employee_documents_type CHECK (document_type IN (
        'PASSPORT','VISA','RESIDENCE_CARD','LABOUR_CARD','CIVIL_ID','EDUCATIONAL_CERTIFICATE',
        'PROFESSIONAL_LICENSE','INSURANCE_CARD','CONTRACT','OFFER_LETTER','OTHER')),
    CONSTRAINT ck_employee_documents_verification CHECK (verification_status IN ('PENDING','VERIFIED','REJECTED')),
    CONSTRAINT ck_employee_documents_issue_expiry CHECK (expiry_date IS NULL OR issue_date IS NULL OR issue_date <= expiry_date)
);

CREATE TABLE IF NOT EXISTS employee.employee_employment_history (
    employment_history_id UUID PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    employee_id UUID NOT NULL,
    action_type VARCHAR(64) NOT NULL,
    old_department_id UUID,
    new_department_id UUID,
    old_designation_id UUID,
    new_designation_id UUID,
    old_location_id UUID,
    new_location_id UUID,
    old_grade_id UUID,
    new_grade_id UUID,
    old_manager_id UUID,
    new_manager_id UUID,
    effective_date DATE NOT NULL,
    remarks VARCHAR(500),
    supporting_document_path VARCHAR(500),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(64) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by VARCHAR(64) NOT NULL,
    CONSTRAINT fk_employee_employment_history_employee FOREIGN KEY (employee_id) REFERENCES employee.employees(id),
    CONSTRAINT ck_employee_employment_history_action CHECK (action_type IN (
        'JOINING','PROMOTION','TRANSFER','SECONDMENT','DESIGNATION_CHANGE','DEPARTMENT_CHANGE',
        'LOCATION_CHANGE','GRADE_CHANGE','REPORTING_MANAGER_CHANGE'))
);

CREATE TABLE IF NOT EXISTS employee.employee_digital_onboarding (
    onboarding_id UUID PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    employee_id UUID NOT NULL,
    onboarding_status VARCHAR(32) NOT NULL,
    eform_completed BOOLEAN NOT NULL DEFAULT FALSE,
    document_upload_completed BOOLEAN NOT NULL DEFAULT FALSE,
    policy_acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
    submitted_date TIMESTAMPTZ,
    reviewed_date TIMESTAMPTZ,
    approved_date TIMESTAMPTZ,
    rejected_reason VARCHAR(500),
    remarks VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(64) NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_by VARCHAR(64) NOT NULL,
    CONSTRAINT fk_employee_digital_onboarding_employee FOREIGN KEY (employee_id) REFERENCES employee.employees(id),
    CONSTRAINT uq_employee_digital_onboarding_tenant_employee UNIQUE (tenant_id, employee_id),
    CONSTRAINT ck_employee_digital_onboarding_status CHECK (onboarding_status IN ('DRAFT','SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED','COMPLETED'))
);

CREATE TABLE IF NOT EXISTS employee.employee_policy_acknowledgements (
    acknowledgement_id UUID PRIMARY KEY,
    tenant_id VARCHAR(64) NOT NULL,
    onboarding_id UUID NOT NULL,
    policy_code VARCHAR(128) NOT NULL,
    policy_version VARCHAR(64) NOT NULL,
    accepted_flag BOOLEAN NOT NULL,
    accepted_date_time TIMESTAMPTZ NOT NULL,
    accepted_by VARCHAR(64),
    remarks VARCHAR(500),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by VARCHAR(64) NOT NULL,
    CONSTRAINT fk_employee_policy_ack_onboarding FOREIGN KEY (onboarding_id) REFERENCES employee.employee_digital_onboarding(onboarding_id)
);

CREATE INDEX IF NOT EXISTS idx_employee_profiles_tenant_status ON employee.employee_profiles (tenant_id, employee_status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_employee_addresses_tenant_employee ON employee.employee_addresses (tenant_id, employee_id, is_active, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_employee_emergency_contacts_tenant_employee ON employee.employee_emergency_contacts (tenant_id, employee_id, is_active, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_employee_dependants_tenant_employee ON employee.employee_dependants (tenant_id, employee_id, is_active, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_employee_beneficiaries_tenant_employee ON employee.employee_beneficiaries (tenant_id, employee_id, is_active, priority_order);
CREATE INDEX IF NOT EXISTS idx_employee_documents_tenant_employee ON employee.employee_documents (tenant_id, employee_id, is_active, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_employee_documents_tenant_expiry ON employee.employee_documents (tenant_id, expiry_date, is_active);
CREATE INDEX IF NOT EXISTS idx_employee_history_tenant_employee ON employee.employee_employment_history (tenant_id, employee_id, effective_date DESC);
