INSERT INTO organization.legal_entities (
    id,
    tenant_id,
    legal_entity_code,
    legal_entity_name,
    short_name,
    registration_no,
    tax_no,
    country_code,
    base_currency_code,
    default_language_code,
    contact_email,
    contact_phone,
    address_line1,
    city,
    state,
    postal_code,
    active,
    created_by,
    updated_by
)
VALUES
    (
        'c3001000-0000-0000-0000-000000000001',
        'default',
        'DEFAULT_HQ',
        'Default Holdings LLC',
        'Default HQ',
        'REG-DEF-001',
        'TAX-DEF-001',
        'OM',
        'OMR',
        'en',
        'hq@default.example.com',
        '+96824000001',
        'Muscat Business District',
        'Muscat',
        'Muscat',
        '100',
        TRUE,
        'SYSTEM_SEED',
        'SYSTEM_SEED'
    ),
    (
        'c3001000-0000-0000-0000-000000000002',
        'lite',
        'LITE_HQ',
        'Lite Services SPC',
        'Lite HQ',
        'REG-LITE-001',
        'TAX-LITE-001',
        'OM',
        'OMR',
        'en',
        'hq@lite.example.com',
        '+96824000002',
        'Seeb Commercial Area',
        'Seeb',
        'Muscat',
        '130',
        TRUE,
        'SYSTEM_SEED',
        'SYSTEM_SEED'
    )
ON CONFLICT (tenant_id, legal_entity_code) DO UPDATE
SET legal_entity_name = EXCLUDED.legal_entity_name,
    short_name = EXCLUDED.short_name,
    registration_no = EXCLUDED.registration_no,
    tax_no = EXCLUDED.tax_no,
    country_code = EXCLUDED.country_code,
    base_currency_code = EXCLUDED.base_currency_code,
    default_language_code = EXCLUDED.default_language_code,
    contact_email = EXCLUDED.contact_email,
    contact_phone = EXCLUDED.contact_phone,
    address_line1 = EXCLUDED.address_line1,
    city = EXCLUDED.city,
    state = EXCLUDED.state,
    postal_code = EXCLUDED.postal_code,
    active = EXCLUDED.active,
    updated_by = 'SYSTEM_SEED',
    updated_at = CURRENT_TIMESTAMP;
