ALTER TABLE master_data.countries
    ADD COLUMN IF NOT EXISTS native_name VARCHAR(128),
    ADD COLUMN IF NOT EXISTS description VARCHAR(255),
    ADD COLUMN IF NOT EXISTS rtl_enabled BOOLEAN NOT NULL DEFAULT FALSE;
